### ISSUE TITLE
Fix publishing workflow

### ISSUE THREAD

**Issue by benjaminbojko** [bluecadet/launchpad#43]
I ran into a few issues when trying to publish the new versioning restructure branch:

- I didn't get an automated action to create a PR that merged changes from develop to main. @claytercek is this supposed to happen with our current config? The versioning PRs I received were only into develop
- I tried to manually publish the repo instead. This worked when CD'ing into `packages/launchpad` and hitting `npm publish`
- Publishing from there worked, but now the NPM page obviously only points to that one package: https://www.npmjs.com/package/@bluecadet/launchpad
- Running `npm i @bluecadet/launchpad` will fail because none of the other packages are published to NPM

@claytercek do you know if all of the above would've been something that the changesets action would've taken care of? Any idea why it might have not run correctly (I probably did something wrong)?

The other issue is that `@bluecadet/launchpad` itself doesn't have a README. @claytercek any thoughts on how we might share the GH readme and the package readme?

The way that changesets does it on their own monorepo doesn't quite seem to work with our flow--their main public package is their [cli](https://www.npmjs.com/package/@changesets/cli), which has a completely different readme than the private [core package](https://github.com/changesets/changesets).

**Comment by benjaminbojko** [comment]
Reverted npm back to `1.0.4` for now.

**Comment by claytercek** [comment]
> I didn't get an automated action to create a PR that merged changes from develop to main. claytercek is this supposed to happen with our current config? The versioning PRs I received were only into develop

@benjaminbojko Yes! This is supposed to happen. Changesets merges into the same branch that's configured as the 'base branch' in the changesets config. There is an extra step during the release workflow that is supposed to merge the changes from `develop` to `main` when all publishes are successful (link below), but it looks like that's not happening. 

https://github.com/bluecadet/launchpad/blob/56298c2cdb924c6b42537401b2d129eeb03862c6/.github/workflows/release.yml#L35-L39

My guess is that the changesets action is probably failing to publish because because it doesn't have permission to create new packages, and none of the sub-packages are up on the registry yet. I think next step is manually publishing all of the sub-packages, then adding another changeset and seeing what happens.

--- 

I'm not sure about the readme... might be worth testing if github and/or npm respect symlinks when displaying readmes?

I just checked out a couple other monorepos to see their solution, and it seems like most treat the root readme as a brief overview, with a 'directory' listing, linking out to each of the packages and their respective changelogs (checkout [shopify's hyrdrogen](https://github.com/Shopify/hydrogen), [xstate](https://github.com/statelyai/xstate), [sveltekit](https://github.com/sveltejs/kit), and [astro](https://github.com/withastro/astro) for some examples).

**Comment by benjaminbojko** [comment]
Thanks, this is all super helpful 🙌. I'll take a look and we can pick this back up next week.

**Comment by claytercek** [comment]
publishing workflow is fixed! It was a combination of the workflow not having permission to publish new packages, _and_ the bluecadetreleases npm account not having access to the launchpad packages because it wasn't on the same npm team that the packages were associated with.

Looking into the readme now!

**Comment by claytercek** [comment]
After some testing, I can confirm that npm does not respect symlinks for readmes, however github does. So, if we'd like the readmes to be mirrored between the root of the gh repo and the npm page for the `@bluecadet/launchpad`, all we have to do is move it to the `packages/launchpad` directory, then make a symlink of it at the repo root with the same name (`README.md`).

**Comment by benjaminbojko** [comment]
That seems like a win-win! How does that look when you check out the project locally on Windows vs Mac OS? Just a regular symlink/shortcut?

**Comment by claytercek** [comment]
Yeah exactly, just a normal symlink

**Comment by benjaminbojko** [comment]
@claytercek do all of the notes in https://github.com/bluecadet/launchpad/blob/main/CONTRIBUTING.md still apply? Anything we need to update for publishing each sub package?

**Comment by benjaminbojko** [comment]
Sweet! I'll follow up with you separately on what instructions to share with the team
