### ISSUE TITLE
Implement app build packaging, distribution and versioning

### ISSUE THREAD

**Issue by benjaminbojko** [bluecadet/launchpad#8]

**Comment by claytercek** [comment]
I did a bit of research here to see what the easiest solution is, and it seems like [changesets](https://github.com/changesets/changesets) is about as simple as it gets. 

There are a handful of similar libraries out there that are also just as if not more popular ([turborepo](https://turborepo.org/), lerna, preconstruct), but changesets is the best option I could find that only really concerns itself with versioning and releasing, instead of also trying to handle building and bundling. In addition, it is also built with monorepos in mind. 

The general idea is, while developing, you can run the `changeset` command to summarize the changes you've made. That command guides you through CLI that helps to associate your changes with the relevant projects, as well as note the importance of the changes. 

```
🦋  Which packages would you like to include? … 
◯ changed packages
  ◉ @bluecadet/launchpad-content
  ◯ @bluecadet/launchpad-core
  ◉ @bluecadet/launchpad-dashboard
  ◯ @bluecadet/launchpad-monitor
  ◯ @bluecadet/launchpad-scaffold
◯ unchanged packages
  ◯ @bluecadet/launchpad-utils

---

🦋  Which packages should have a major bump? … 
◯ all packages
  ◉ @bluecadet/launchpad-content@1.0.1
  ◯ @bluecadet/launchpad-dashboard@1.0.1

---

🦋  Which packages should have a minor bump? … 
◯ all packages
  ◉ @bluecadet/launchpad-dashboard@1.0.1

---

🦋  Please enter a summary for this change (this will be in the changelogs).
🦋    (submit empty line to open external editor)
🦋  Summary ‣  [your summary message]
```

Once you've made a handful of these 'changesets' and are ready to release a new version, you just have to run `changeset version` command, which goes through each of the summaries you've logged and increments the version number of each package accordingly, and adds the summaries to their respective changelogs.

It also will update the `package.json` file for any packages in the monorepo that depend on the changed packages, so if you update `@bluecadet/launchpad-content` with a minor patch from `1.0.1` to `1.1.1`,  the version referenced in the `@bluecadet/launchpad` `package.json` will be updated accordingly. 

Finally, running `changesets release` will go through each package in your monorepo, and publish the latest version to npm if the local version number is greater than the version currently on the registry.

The other great thing is that the last two steps are _super_ easy to automate with a [first party github action](https://github.com/changesets/action).

I did some testing with setting up changesets on the [feature/versioning](https://github.com/bluecadet/launchpad/tree/feature/versioning) branch.


### One small issue 😢:

changesets does expect the monorepo to be built in a more 'flat'/classic monorepo file structure, where the root `package.json` is just used to link up the workspaces, rather than the way we've structured it where the root describes a parent package that references the child packages in workspaces. 

There might be some combination of `package.json` settings and changeset config settings that would make this structure work, but it's also pretty easy to update the repo to match the expected structure, shown on the [feature/versioning-restructure](https://github.com/bluecadet/launchpad/tree/feature/versioning-restructure) branch. I moved the logic that was at the root of the repo to the `core` package directory, so that that directory is now the `@bluecadet/launchpad` package.

**Comment by benjaminbojko** [comment]
Oooh, this is really interesting. Thanks for investigating! I remember there being quite a bit of trickiness when I tried using NPM's workspaces at the time. That's why I had to repeat all the child package dependencies, e.g. But that was also with Node 17.5.0, so maybe things have gotten better? Were you able to run `npm install` with this setup? Did you have to link the child packages or was everything able to run from the project folder?

**Comment by claytercek** [comment]
Yep! Everything seems to be working. Right now I'm using 
```
node: 16.0.0
npm: 7.10.0
windows: 10.0.19043
```
